Revise checks for revision consistency
brightway-lca/brightway2-data pull request #207
Opened 2024-11-09 10:16 UTC by cmutel

2024-11-11 11:07 UTC, bbguimaraes commented on bw2data/project.py
> +            self.is_sourced = True
It's a bit surprising that applying a revision performs this operation, but we should at least call `set_sourced`, since there are already additional operations there and more could possibly be added in the future.

2024-11-11 11:07 UTC, bbguimaraes commented on bw2data/project.py
> +            raise InconsistentData
This would be a good candidate for a separate function which could be reused and tested, but that can be left for a future enhancement.

2024-11-11 12:52 UTC, cmutel commented on bw2data/project.py
> +            self.is_sourced = True
@bbguimaraes Thanks.

The right answer here is probably that we shouldn't allow diffs to be applied unless we know the starting state. But I think that ship has left the port. IMHO it is much safer to start tracking revisions as soon as possible.

2024-11-11 14:17 UTC, jsvgoncalves requested changes

2024-11-11 14:17 UTC, jsvgoncalves commented on bw2data/project.py
> +            self.is_sourced = True
We should definitely call `set_sourced()` instead of `self.is_sourced = True`.

2024-11-14 09:18 UTC, jsvgoncalves approved these changes

2024-11-14 09:19 UTC, merged